project/apps/parlamentares/urls.py
from django.urls import path

from . import views

app_name = 'parlamentares'

urlpatterns = [
        path('', views.BuscaView.as_view(), name='busca'),
        path('parlamentar/<id>/', views.ParlamentarView.as_view(), name='detail'),
        path('estados/', views.EstadosView.as_view(), name='estados'),
        path('estados/<uf>/', views.EstadoView.as_view(), name='estado'),
]

project/apps/parlamentares/views.py
import httpx
import json
from django.views.generic import View
from django.shortcuts import render
from django.contrib import messages


class BuscaView(View):
    template_name = "parlamentares/busca.html"
    
    def get(self, request, *args, **kwargs):
        context = {}
        if 'nome' in request.GET:
            nome = request.GET.get('nome')
            
            with httpx.Client() as client:
                try:
                    r = client.get(f"https://dadosabertos.camara.leg.br/api/v2/deputados?nome={nome}&ordem=ASC&ordenarPor=nome", timeout=1)
                    response = r.json()
                    if response:
                        context['parlamentares'] = response['dados']
            
                except httpx.TimeoutException as e:
                    messages.error(self.request, f'OPS! Parece que a API de dados abertos está fora do ar... =/')
                    return render(request, self.template_name, context)
                except Exception as e:
                    return render(request, self.template_name, context)
                
        
        
        return render(request, self.template_name, context)


class ParlamentarView(View):
    template_name = "parlamentares/detail.html"
    
    def get(self, request, *args, **kwargs):
        context = {}
        id_deputado = kwargs.get('id', None)
        if id_deputado is not None:
            with httpx.Client() as client:
                try:
                    r = httpx.get(f"https://dadosabertos.camara.leg.br/api/v2/deputados/{id_deputado}", timeout=1)
                    response = r.json()
                    if response:
                        context['dados_parlamentar'] = response['dados']
                    
                    r = httpx.get(f"https://dadosabertos.camara.leg.br/api/v2/deputados/{id_deputado}/ocupacoes", timeout=1)
                    response = r.json()
                    if response:
                        context['curriculo'] = response['dados']
            
                except httpx.TimeoutException as e:
                    messages.error(self.request, f'OPS! Parece que a API de dados abertos está fora do ar... =/')
                    return render(request, self.template_name, context)
                except Exception as e:
                    return render(request, self.template_name, context)
                
   
            
        return render(request, self.template_name, context)
    
class EstadosView(View):
    template_name = "parlamentares/estados.html"
    
    def get(self, request, *args, **kwargs):
        context = {}
        with httpx.Client() as client:
            try:
                r = httpx.get("https://dadosabertos.camara.leg.br/api/v2/referencias/deputados/siglaUF", timeout=1)
                response = r.json()
                if response:
                    context['UFs'] = response['dados']
            except httpx.TimeoutException as e:
                messages.error(self.request, f'OPS! Parece que a API de dados abertos está fora do ar... =/')
                return render(request, self.template_name, context)
            except Exception as e:
                return render(request, self.template_name, context)
            
   
            
        return render(request, self.template_name, context)

class EstadoView(View):
    template_name = "parlamentares/estado.html"
    
    def get(self, request, *args, **kwargs):
        context = {}
        uf = kwargs.get('uf', None)
        
        sigla_nome = {
            'ac' : 'Acre',
            'al' : 'Alagoas',
            'am' : 'Amazonas',
            'ap' : 'Amapá',
            'ba' : 'Bahia',
            'ce' : 'Ceará',
            'df' : 'Distrito Federal',
            'es' : 'Espírito Santo',
            'go' : 'Goiás',
            'ma' : 'Maranhão',
            'mg' : 'Minas Gerais',
            'ms' : 'Mato Grosso do Sul',
            'mt' : 'Mato Grosso',
            'pa' : 'Pará',
            'pb' : 'Paraíba',
            'pe' : 'Pernambuco',
            'pb' : 'Paraíba',
            'pi' : 'Piauí',
            'pr' : 'Paraná',
            'rj' : 'Rio de Janeiro',
            'rn' : 'Rio Grande do Norte',
            'ro' : 'Rondônia',
            'rr' : 'Roraima',
            'rs' : 'Rio Grande do Sul',
            'sc' : 'Santa Catarina',
            'se' : 'Sergipe',
            'sp' : 'São Paulo',
            'to' : 'Tocantins',
        }
        
        if uf is not None:
            with httpx.Client() as client:
                try:
                    r = client.get(f"https://dadosabertos.camara.leg.br/api/v2/deputados?siglaUf={uf}&ordem=ASC&ordenarPor=nome", timeout=1)
                    response = r.json()
                    if response:
                        context['parlamentares'] = response['dados']
                    context['uf_nome'] = sigla_nome[uf.lower()]
                    
                except httpx.TimeoutException as e:
                    messages.error(self.request, f'OPS! Parece que a API de dados abertos está fora do ar... =/')
                    return render(request, self.template_name, context)
                except Exception as e:
                    return render(request, self.template_name, context)
            
   
            
        return render(request, self.template_name, context)

project/apps/parlamentares/templates/parlamentares/busca.html
{% extends "base.html" %}

{% block body %}
<div class="row justify-content-center mt-4">
  <div class="col-12 col-md-8 px-4 px-md-0">
    
    <form class="d-flex flex-row align-items-center m-0 p-0" action="" method="get">
      <input type="text" name="nome" id="id_nome" class="form-control  mx-1 " placeholder="Escreva o nome do parlamentar">    
      <input class="btn btn-secondary mx-1" type="submit" value="Buscar" />
    </form>
    
    {% if 'nome' in request.GET and not parlamentares %} 
      <div class="row justify-content-center">
        <div class="col text-center">
          Nenhum parlamentar encontrado.
        </div>
      </div>
    {% endif %}

    {% for parlamentar in parlamentares %}
      
      <div class="row my-2" style="min-height:200px;">
        <div class="card p-3 bg-light shadow-sm">
          <div class="row no-gutters">
            <div class="col-auto position-relative">
              <img src="{{parlamentar.urlFoto}}" class="img-fluid foto-img shadow-sm" width=100>  
            </div>
            <div class="col">
              
              <h4 class="card-title fs-6"><b>{{parlamentar.nome}}</b></h4>
              <hr>
              
              <div>
                <p class=" card-text m-0"><b>UF:</b> {{parlamentar.siglaUf}}</p>
                <p class="card-text m-0"><b>Partido:</b> {{parlamentar.siglaPartido}}</p>
              </div>
              
              <a href="{% url 'parlamentares:detail' parlamentar.id %}" class="stretched-link"></a>

            </div>
          </div>
        </div>

        
      </div>
    {% endfor %}

  </div>

</div>

{% endblock %}

project/apps/parlamentares/templates/parlamentares/detail.html
{% extends "base.html" %}

{% block body %}
<div class="row justify-content-center mt-4">
  <div class="col-8">
  
  {% if request.path in request.META.HTTP_REFERER %} 
    <a href="{% url 'parlamentares:busca' %}" class="btn btn-secondary">Voltar</a>
  {% else %}
    <a href="{{request.META.HTTP_REFERER}}" class="btn btn-secondary">Voltar</a>
  {% endif %}

    <div class="row my-2" style="min-height:40px;">
      
      <div class="card p-3 bg-light shadow-sm">
        <div class="row no-gutters">
          <div class="col-auto position-relative">
            <img src="{{dados_parlamentar.ultimoStatus.urlFoto}}" class="img-fluid shadow-sm" width="250">  
          </div>
          <div class="col">
            
            <h3 class="card-title fs-5"><b>{{dados_parlamentar.nomeCivil|default:""}}</b></h3>
            <p class="card-text m-0">Data Nascimento: {{dados_parlamentar.dataNascimento|default:""}}</p>
            <hr>
            
            <div>
              <p class="card-text m-0"><b>Nome Eleitoral:</b> {{dados_parlamentar.ultimoStatus.nomeEleitoral|default:""}}</p>
              <p class=" card-text m-0"><b>UF:</b> {{dados_parlamentar.ultimoStatus.siglaUf|default:""}}</p>
              <p class="card-text m-0"><b>Partido:</b> {{dados_parlamentar.ultimoStatus.siglaPartido|default:""}}</p>
              <p class="card-text m-0"><b>Situação:</b> {{dados_parlamentar.ultimoStatus.situacao|default:""}}</p>
              <p class="card-text m-0"><b>Condição Eleitoral:</b> {{dados_parlamentar.ultimoStatus.condicaoEleitoral|default:""}}</p>

              <br>
              <p class="card-text m-0"><b>Gabinete:</b>
                Prédio: {{dados_parlamentar.ultimoStatus.gabinete.predio|default:""}},
                Sala: {{dados_parlamentar.ultimoStatus.gabinete.sala|default:""}}, 
                Andar: {{dados_parlamentar.ultimoStatus.gabinete.andar|default:""}}.
                Telefone: {{dados_parlamentar.ultimoStatus.gabinete.telefone|default:""}}
              </p>
              <br>

            </div>
          </div>
        </div>
      </div>


      <div class="card p-3 bg-light shadow-sm">
          <h3 class="card-title fs-3"><b>Curriculo</b></h3>
          <div>
            {% for ocupacao in curriculo %}
              <hr>
              <h3 class="card-title fs-5 mb-0"><b>{{ocupacao.titulo}}</b></h3>
              {% if ocupacao.entidadePais%}
                {{ocupacao.entidadePais|default:""}}/{{ocupacao.entidadeUF|default:""}}
              {% endif %}
              {% if ocupacao.entidade%}
              <p class="card-text mt-1 mb-0"><b>Entidade:</b> {{ocupacao.entidade|default:""}}</p>
              {% endif %}
              <p class="card-text m-0">{% if ocupacao.anoInicio %}<b>Início:</b> {{ocupacao.anoInicio|default:""}} {% endif %}{% if ocupacao.anoFim %}<b>Fim:</b> {{ocupacao.anoFim|default:""}}{% endif %}</p>
      
            {% endfor %}  
          </div>
      </div>




    </div>

  </div>

</div>

{% endblock %}

project/apps/parlamentares/templates/parlamentares/estado.html
{% extends "base.html" %}

{% block body %}
<div class="row justify-content-center mt-4">
  <div class="col-12 col-md-8 px-5 px-md-0">
  <a href="{% url 'parlamentares:estados' %}" class="btn btn-secondary">Voltar</a>
  <div class='row my-3'>
    <h3 class='fs-4 text-center'> Deputados do Estado: <b class='fs-2'>{{uf_nome}}</b></h3>
  </div>
{% for parlamentar in parlamentares %}
      
<div class="row my-2" style="min-height:200px;">
  <div class="card p-3 bg-light shadow-sm">
    <div class="row no-gutters">
      <div class="col-auto position-relative">
        <img src="{{parlamentar.urlFoto}}" class="img-fluid foto-img shadow-sm" width=100>  
      </div>
      <div class="col">
        
        <h4 class="card-title fs-6"><b>{{parlamentar.nome}}</b></h4>
        <hr>
        
        <div>
          <p class=" card-text m-0"><b>UF:</b> {{parlamentar.siglaUf}}</p>
          <p class="card-text m-0"><b>Partido:</b> {{parlamentar.siglaPartido}}</p>
        </div>
        
        <a href="{% url 'parlamentares:detail' parlamentar.id %}" class="stretched-link"></a>

      </div>
    </div>
  </div>

  
</div>
{% endfor %}
</div>
</div>
{% endblock %}

project/apps/parlamentares/templates/parlamentares/estados.html
{% extends "base.html" %}

{% block css %}
<style type="text/css">
  .active { display:inherit; }
  ul#map {display: block; margin: 0; padding: 0; width: 570px; height: 585px; background-image: url('/static/img/map.gif');}
  ul#map li {display: block; padding: 0; position: absolute;}
  li#crs {margin-top: 485px; margin-left: 237px; }
  li#csc {margin-top: 467px; margin-left: 292px;}
  li#cpr {margin-top: 416px; margin-left: 281px;}
  li#csp {margin-top: 375px; margin-left: 303px; z-index:9999; }
  li#cms {margin-top: 336px; margin-left: 229px;}
  li#crj {margin-top: 390px; margin-left: 422px; z-index:9999; }
  li#ces {margin-top: 347px; margin-left: 467px; z-index:9999; }
  li#cmg {margin-top: 292px; margin-left: 333px; z-index:9998; }
  li#cgo {margin-top: 264px; margin-left: 301px; z-index:9999; }
  li#cdf {margin-top: 311px; margin-left: 373px; z-index:9999; }
  li#cba {margin-top: 207px; margin-left: 397px;}
  li#cmt {margin-top: 189px; margin-left: 180px;}
  li#cro {margin-top: 199px; margin-left: 104px; z-index:9998; }
  li#cac {margin-top: 185px; margin-left: 0px;}
  li#cam {margin-top: 46px; margin-left: 3px;}
  li#crr {margin-top: 0; margin-left: 133px;}
  li#cpa {margin-top: 40px; margin-left: 219px;}
  li#cap {margin-top: 13px; margin-left: 278px;}
  li#cma {margin-top: 94px; margin-left: 366px; z-index:9999;}
  li#cto {margin-top: 156px; margin-left: 338px;}

  li#cse {margin-top: 221px; margin-left: 519px; z-index:9998;}
  li#cal {margin-top: 211px; margin-left: 518px; z-index:9999;}
  li#cpe {margin-top: 188px; margin-left: 473px;}
  li#cpb {margin-top: 169px; margin-left: 511px; z-index:9999;}
  li#crn {margin-top: 151px; margin-left: 514px;}
  li#cce {margin-top: 121px; margin-left: 473px;}
  li#cpi {margin-top: 120px; margin-left: 406px; z-index:9997;}

  ul#map li a {display: block; text-decoration: none; position: absolute;}
  a#rs {width: 116px; height: 101px; }
  a#sc {width: 81px; height: 53px; }
  a#pr {width: 97px; height: 64px; }
  a#sp {width: 131px; height: 84px; }
  a#ms {width: 106px; height: 104px; }
  a#rj {width: 58px; height: 40px; }
  a#es {width: 33px; height: 51px; }
  a#mg {width: 163px; height: 131px; }
  a#go {width: 108px; height: 108px; }
  a#df {width: 16px; height: 9px; }
  a#ba {width: 136px; height: 148px; }
  a#mt {width: 166px; height: 161px; }
  a#ro {width: 104px; height: 87px; }
  a#ac {width: 108px; height: 62px; }
  a#am {width: 258px; height: 181px;}
  a#rr {width: 87px; height: 103px; }
  a#pa {width: 188px; height: 187px; }
  a#ap {width: 73px; height: 85px; }
  a#ma {width: 102px; height: 139px; }
  a#to {width: 74px; height: 125px; }
  a#se {width: 28px; height: 32px; }
  a#al {width: 46px; height: 27px; }
  a#pe {width: 97px; height: 34px; }
  a#pb {width: 59px; height: 35px; }
  a#rn {width: 53px; height: 33px; }
  a#ce {width: 61px; height: 76px; }
  a#pi {width: 83px; height: 124px; }

  /* Código pronto via http://css.spritegen.com (com alterações nos seletores) */

  a#pa:hover, a#pa:active, a#am:hover, a#am:active, a#mt:hover, a#mt:active, a#ba:hover, a#ba:active, a#ma:hover, a#ma:active,
  a#mg:hover, a#mg:active, a#to:hover, a#to:active, a#pi:hover, a#pi:active, a#go:hover, a#go:active, a#ms:hover, a#ms:active,
  a#rr:hover, a#rr:active, a#rs:hover, a#rs:active, a#ro:hover, a#ro:active, a#ap:hover, a#ap:active, a#sp:hover, a#sp:active,
  a#ce:hover, a#ce:active, a#pr:hover, a#pr:active, a#ac:hover, a#ac:active, a#sc:hover, a#sc:active, a#es:hover, a#es:active,
  a#rj:hover, a#rj:active, a#pb:hover, a#pb:active, a#pe:hover, a#pe:active, a#rn:hover, a#rn:active, a#se:hover, a#se:active,
  a#al:hover, a#al:active, a#df:hover, a#df:active
  { display: block; background: url('/static/img/sprite.gif') no-repeat; }

  a#pa:hover, a#pa:active { background-position: -10px -0px; width: 188px; height: 187px; }
  a#am:hover, a#am:active { background-position: -10px -197px; width: 258px; height: 181px; }
  a#mt:hover, a#mt:active { background-position: -10px -388px; width: 166px; height: 161px; }
  a#ba:hover, a#ba:active { background-position: -10px -559px; width: 136px; height: 148px; }
  a#ma:hover, a#ma:active { background-position: -156px -559px; width: 102px; height: 139px; }
  a#mg:hover, a#mg:active { background-position: -10px -717px; width: 163px; height: 131px; }
  a#to:hover, a#to:active { background-position: -183px -717px; width: 74px; height: 125px; }
  a#pi:hover, a#pi:active { background-position: -10px -858px; width: 83px; height: 124px; }
  a#go:hover, a#go:active { background-position: -103px -858px; width: 108px; height: 108px; }
  a#ms:hover, a#ms:active { background-position: -103px -976px; width: 106px; height: 104px; }
  a#rr:hover, a#rr:active { background-position: -10px -992px; width: 87px; height: 103px; }
  a#rs:hover, a#rs:active { background-position: -107px -1090px; width: 116px; height: 101px; }
  a#ro:hover, a#ro:active { background-position: -10px -1201px; width: 104px; height: 87px; }
  a#ap:hover, a#ap:active { background-position: -10px -1105px; width: 73px; height: 85px; }
  a#sp:hover, a#sp:active { background-position: -124px -1201px; width: 131px; height: 84px; }
  a#ce:hover, a#ce:active { background-position: -186px -388px; width: 61px; height: 76px; }
  a#pr:hover, a#pr:active { background-position: -124px -1295px; width: 97px; height: 64px; }
  a#ac:hover, a#ac:active { background-position: -10px -1298px; width: 108px; height: 62px; }
  a#sc:hover, a#sc:active { background-position: -128px -1369px; width: 81px; height: 53px; }
  a#es:hover, a#es:active { background-position: -208px -0px; width: 33px; height: 51px; }
  a#rj:hover, a#rj:active { background-position: -186px -474px; width: 58px; height: 40px; }
  a#pb:hover, a#pb:active { background-position: -10px -1370px; width: 59px; height: 35px; }
  a#pe:hover, a#pe:active { background-position: -10px -1415px; width: 97px; height: 34px; }
  a#rn:hover, a#rn:active { background-position: -186px -524px; width: 53px; height: 33px; }
  a#se:hover, a#se:active { background-position: -208px -61px; width: 28px; height: 32px; }
  a#al:hover, a#al:active { background-position: -208px -103px; width: 46px; height: 27px; }
  a#df:hover, a#df:active { background-position: -208px -140px; width: 16px; height: 9px; }

  /* Fim sprite */

  ul#map li a img {border: 0; width: inherit; height: inherit;}
</style>
{% endblock %}

{% block body %}
<div class="row justify-content-center mt-4">
    <div class='row my-3'>
      <h3 class='fs-4 text-center'> Selecione o Estado: <b class='fs-2'>{{uf_nome}}</b></h3>
    </div>
  
    <ul class="col-4" id="map" class="text-center">
			<li id="crs" estado="rs"><a href="/estados/rs" id="rs" title="RS"><img src="/static/img/null.gif" alt="RS" /></a></li>
			<li id="csc" estado="sc"><a href="/estados/sc" id="sc" title="SC"><img src="/static/img/null.gif" alt="SC" /></a></li>
			<li id="cpr" estado="pr"><a href="/estados/pr" id="pr" title="PR"><img src="/static/img/null.gif" alt="PR" /></a></li>
			<li id="csp" estado="sp"><a href="/estados/sp" id="sp" title="SP"><img src="/static/img/null.gif" alt="SP" /></a></li>
			<li id="cms" estado="ms"><a href="/estados/ms" id="ms" title="MS"><img src="/static/img/null.gif" alt="MS" /></a></li>
			<li id="crj" estado="rj"><a href="/estados/rj" id="rj" title="RJ"><img src="/static/img/null.gif" alt="RJ" /></a></li>
			<li id="ces" estado="es"><a href="/estados/es" id="es" title="ES"><img src="/static/img/null.gif" alt="ES" /></a></li>
			<li id="cmg" estado="mg"><a href="/estados/mg" id="mg" title="MG"><img src="/static/img/null.gif" alt="MG" /></a></li>
			<li id="cgo" estado="go"><a href="/estados/go" id="go" title="GO"><img src="/static/img/null.gif" alt="GO" /></a></li>
			<li id="cdf" estado="df"><a href="/estados/df" id="df" title="DF"><img src="/static/img/null.gif" alt="DF" /></a></li>
			<li id="cba" estado="ba"><a href="/estados/ba" id="ba" title="BA"><img src="/static/img/null.gif" alt="BA" /></a></li>
			<li id="cmt" estado="mt"><a href="/estados/mt" id="mt" title="MT"><img src="/static/img/null.gif" alt="MT" /></a></li>
			<li id="cro" estado="ro"><a href="/estados/ro" id="ro" title="RO"><img src="/static/img/null.gif" alt="RO" /></a></li>
			<li id="cac" estado="ac"><a href="/estados/ac" id="ac" title="AC"><img src="/static/img/null.gif" alt="AC" /></a></li>
			<li id="cam" estado="am"><a href="/estados/am" id="am" title="AM"><img src="/static/img/null.gif" alt="AM" /></a></li>
			<li id="crr" estado="rr"><a href="/estados/rr" id="rr" title="RR"><img src="/static/img/null.gif" alt="RR" /></a></li>
			<li id="cpa" estado="pa"><a href="/estados/pa" id="pa" title="PA"><img src="/static/img/null.gif" alt="PA" /></a></li>
			<li id="cap" estado="ap"><a href="/estados/ap" id="ap" title="AP"><img src="/static/img/null.gif" alt="AP" /></a></li>
			<li id="cma" estado="ma"><a href="/estados/ma" id="ma" title="MA"><img src="/static/img/null.gif" alt="MA" /></a></li>
			<li id="cto" estado="to"><a href="/estados/to" id="to" title="TO"><img src="/static/img/null.gif" alt="TO" /></a></li>
			<li id="cse" estado="se"><a href="/estados/se" id="se" title="SE"><img src="/static/img/null.gif" alt="SE" /></a></li>
			<li id="cal" estado="al"><a href="/estados/al" id="al" title="AL"><img src="/static/img/null.gif" alt="AL" /></a></li>
			<li id="cpe" estado="pe"><a href="/estados/pe" id="pe" title="PE"><img src="/static/img/null.gif" alt="PE" /></a></li>
			<li id="cpb" estado="pb"><a href="/estados/pb" id="pb" title="PB"><img src="/static/img/null.gif" alt="PB" /></a></li>
			<li id="crn" estado="rn"><a href="/estados/rn" id="rn" title="RN"><img src="/static/img/null.gif" alt="RN" /></a></li>
			<li id="cce" estado="ce"><a href="/estados/ce" id="ce" title="CE"><img src="/static/img/null.gif" alt="CE" /></a></li>
			<li id="cpi" estado="pi"><a href="/estados/pi" id="pi" title="PI"><img src="/static/img/null.gif" alt="PI" /></a></li>
		</ul>
  

</div>

{% endblock %}